### ISSUE TITLE
从旧的脚本升级到最新的脚本后显示找不到脚本

### ISSUE THREAD

**Issue by sdshdv** [Jrohy/multi-v2ray#188]
本来用的好好的,升级了一下脚本,结果悲剧了
提示如下:
multi-v2ray install success!
-bash: /usr/local/bin/v2ray: No such file or directory
please input 'v2ray' command to manage v2ray

输入V2RAY之后脚本直接显示No such file or directory了

**Comment by Jrohy** [comment]
v2ray-util命令能用吗

**Comment by LeeQin123** [comment]
我也是这个问题，v2ray-util也不能用

**Comment by Jrohy** [comment]
@LeeQin123 `which v2ray-util`显示什么呢

**Comment by Jrohy** [comment]
会不会pip没安装上

**Comment by LeeQin123** [comment]
@Jrohy 
which: no v2ray-util in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
pip安装好的,pip版本信息：
pip 19.0.3 from /usr/lib/python3.6/site-packages/pip (python 3.6)

**Comment by LeeQin123** [comment]
@Jrohy 更新过程有报错
Could not fetch URL https://pypi.org/simple/v2ray-util/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/v2ray-util/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) - skipping
  Could not find a version that satisfies the requirement v2ray_util (from versions: )
No matching distribution found for v2ray_util

**Comment by sdshdv** [comment]
我输入v2ray-util之后显示-bash: v2ray-util: command not found  输入which v2ray-util之后提示和上面这位一样

**Comment by Jrohy** [comment]
没安装到v2ray-util, 可以手动安装下`pip3 install v2ray-util`

**Comment by Jrohy** [comment]
这是pip源: https://pypi.org/project/v2ray-util/

**Comment by LeeQin123** [comment]
解决了，安装v2ray-util时，可能会报ssl错误，自己手动安装一下就好了
